// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ6td8HPAt93lyskk7x8pHmTebxLKCP9U',
    appId: '1:895161891322:web:79dbf4915f90571f544c43',
    messagingSenderId: '895161891322',
    projectId: 'flutter-game-app-55ec2',
    authDomain: 'flutter-game-app-55ec2.firebaseapp.com',
    storageBucket: 'flutter-game-app-55ec2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcA8gSqNeASrW4Sgzr8b99klSytz5tFwM',
    appId: '1:895161891322:android:933d0f23229e2bda544c43',
    messagingSenderId: '895161891322',
    projectId: 'flutter-game-app-55ec2',
    storageBucket: 'flutter-game-app-55ec2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYa0RXR5pF3xS6-d7PEaSKHnF1rf3CRWw',
    appId: '1:895161891322:ios:c09e071bf19b283e544c43',
    messagingSenderId: '895161891322',
    projectId: 'flutter-game-app-55ec2',
    storageBucket: 'flutter-game-app-55ec2.firebasestorage.app',
    iosBundleId: 'com.example.gameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYa0RXR5pF3xS6-d7PEaSKHnF1rf3CRWw',
    appId: '1:895161891322:ios:c09e071bf19b283e544c43',
    messagingSenderId: '895161891322',
    projectId: 'flutter-game-app-55ec2',
    storageBucket: 'flutter-game-app-55ec2.firebasestorage.app',
    iosBundleId: 'com.example.gameApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ6td8HPAt93lyskk7x8pHmTebxLKCP9U',
    appId: '1:895161891322:web:dd8b1e95d6217843544c43',
    messagingSenderId: '895161891322',
    projectId: 'flutter-game-app-55ec2',
    authDomain: 'flutter-game-app-55ec2.firebaseapp.com',
    storageBucket: 'flutter-game-app-55ec2.firebasestorage.app',
  );
}
